[env:heltec_wifi_lora_32_V4]
platform = espressif32
board = heltec_wifi_lora_32_V4
framework = arduino
board_build.variants_dir = variants
board_build.variant = heltec_V4
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1

monitor_speed = 115200  
monitor_dtr = 0
monitor_rts = 0
lib_deps =
    https://github.com/Reticulum-Community/microReticulum
    https://github.com/attermann/microStore.git
    rweather/Crypto@0.4.0
    bblanchon/ArduinoJson
    hideakitai/MsgPack
